# Generated by Django 3.2.7 on 2021-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210905_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
