# Generated by Django 3.2.7 on 2021-09-05 12:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
