# Generated by Django 3.2.7 on 2021-09-05 12:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.AlterModelTable(
            name='newsmodel',
            table='News',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='kategoriler',
            field=models.ManyToManyField(related_name='content', to='news.CategoryModel'),
        ),
    ]
