# Generated by Django 3.2.7 on 2021-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210905_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='kategoriler',
            new_name='category',
        ),
    ]
