# Generated by Django 3.2.7 on 2021-09-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_kategoriler_newsmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='category',
        ),
    ]
