# Generated by Django 3.2.7 on 2021-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_newsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='category',
            field=models.ManyToManyField(related_name='content', to='news.CategoryModel'),
        ),
    ]
